main: ${plugin.mainClass}
name: ${plugin.name}
version: ${plugin.version}
description: ${plugin.description}
authors:
  - Manunu_
website: https://github.com/Manu585/JustEnoughAbilities
api-version: 1.21
depend:
  - ProjectKorra
  - packetevents