main: ${plugin.mainClass}
name: ${plugin.name}
version: ${plugin.version}
description: ${plugin.description}
author: ${plugin.author}
website: https://github.com/Manu585/CisCov
api-version: 1.21
depend:
  - ProjectKorra
  - packetevents